### ISSUE TITLE
HDMI audio support Rpi4

### ISSUE THREAD

**Issue by AlexGellert-zz** [SpottyMatt/raspbian-stepmania-build#4]
Currently I have not Managed to get HDMI audio working on stepmania for Rpi4.
Using the latest raspbian, it has the latest ALSA. I even forced hdmi=2 and edited the sound settings SoundDriver=plughw:2,0 with ALSA-sw.

The HDMI audio does work on all the tv's using youtube or other programs.

Kind mikemintz has a fix.

> I ran into the same issue on my 4b, and I was able to resolve it by modifying ~/.stepmania-5.1/Save/Preferences.ini and setting `SoundWriteAhead=2048`
> 
> My guess is that the `WARNING: ALSA: snd_pcm_wait: Broken pipe` log messages indicated buffer underruns.

**Comment by ColonelPanics** [comment]
I've been in the same position for months, wasn't aware of the forcing and settings that can be changed as you mentioned so will look at that too.

Is there anything else you tried to get it work? The docs here seem to indicate that sound would work but be scratchy but it doesn't seem to be the case 😖

**Comment by AlexGellert-zz** [comment]
> I've been in the same position for months, wasn't aware of the forcing and settings that can be changed as you mentioned so will look at that too.
> 
> Is there anything else you tried to get it work? The docs here seem to indicate that sound would work but be scratchy but it doesn't seem to be the case 😖

So I tried reading through the setup code itself and prevent the usb sound card audio from being set, i don't know if this is even a viable option.  @SpottyMatt any tips on where this might lay in the repo? The forcing plughw works for any sound device not just HDMI but I believe stepmania setup is specifically configured for USB audio. I tried a USB speaker and it worked fine but it took up too much power.

**Comment by ColonelPanics** [comment]
From the looks of things, neither the patch or the make options are forcing SM to use USB audio only (from what I can see). 

The confusing thing is that the initial launch looks to be using the correct ALSA output
```
pi@openpartynight:~/COMPILE/raspbian-stepmania-build $ ./stepmania/stepmania
StepMania5.1.0
Compiled 20201030 @ 14:35:48 (build 6a645b4710)
Log starting 2020-10-30 15:10:33
Loading window: gtk
OS: Linux ver 050472
Runtime library: glibc 2.28
Threads library: NPTL 2.28
libavcodec: 0x372765 (3614565)
ALSA: Advanced Linux Sound Architecture Driver Version k5.4.72-v7l+.
ALSA Driver: 0: bcm2835 HDMI 1 [b1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1], 4/4 subdevices avail
ALSA Driver: 1: bcm2835 Headphones [Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones], 4/4 subdevices avail
ALSA: Mixing at 44100hz
ALSA: chunksize adjusted from 64 to 444
Sound driver: ALSA-sw
Lights driver: SystemMessage
Lights driver: Export
/////////////////////////////////////////
WARNING: ALSA: snd_pcm_wait: Broken pipe
/////////////////////////////////////////
```

**Comment by ColonelPanics** [comment]
It might be worth tweaking the cmake options to use a different audio driver as described at https://github.com/stepmania/stepmania/issues/1846#issuecomment-516521086

**Comment by ColonelPanics** [comment]
Looks like mine is trying to use ALSA & PulseAudio, might try with Jack audio...

```
pi@openpartynight:~/COMPILE/raspbian-stepmania-build/stepmania $ grep -R WITH_ALSA
CMake/DefineOptions.cmake:  option(WITH_ALSA "Build with ALSA support" ON)
CMakeCache.txt:WITH_ALSA:BOOL=ON
StepmaniaCore.cmake:  if(WITH_ALSA)
pi@openpartynight:~/COMPILE/raspbian-stepmania-build/stepmania $ grep -R WITH_JACK
CMake/DefineOptions.cmake:  option(WITH_JACK "Build with JACK support" OFF)
CMakeCache.txt:WITH_JACK:BOOL=OFF
StepmaniaCore.cmake:  if(WITH_JACK)
pi@openpartynight:~/COMPILE/raspbian-stepmania-build/stepmania $ grep -R WITH_PULSE
CMake/DefineOptions.cmake:  option(WITH_PULSEAUDIO "Build with PulseAudio support" ON)
CMakeCache.txt:WITH_PULSEAUDIO:BOOL=ON
StepmaniaCore.cmake:  if(WITH_PULSEAUDIO)
```

**Comment by SpottyMatt** [comment]
Firstly, this is odd since HDMI out is usually the default for RPi audio, when you plug an HDMI cable into a speaker-equipped HDMI display. It was on the 3b and 3b+, anyway.

> The docs here seem to indicate that sound would work but be scratchy but it doesn't seem to be the case

Disclaimer: I haven't used HDMI audio out on the RPi4 yet; my "disable HDMI and force USB audio" code was perfected on the RPi3 generation, and worked on the 4, so I've never actually heard what HDMI audio for stepmania sounds like on the RPi4.

On the 3B and 3B+, the onboard sound card couldn't keep up with StepMania's demands, and the integrated HDMI audio out would be scratchy and distorted.

> So I tried reading through the setup code itself and prevent the usb sound card audio from being set, i don't know if this is even a viable option. @SpottyMatt any tips on where this might lay in the repo? 

This setting is an RPi setting, _not_ a stepmania setting, so **this is technically not the right place for the discussion**; you won't find the answer in this repo. The answer is here: https://github.com/SpottyMatt/raspbian-stepmania-arcade/blob/master/system-prep/usb-audio-by-default.conf , configuration which is added to `/etc/modprobe.d/` here: https://github.com/SpottyMatt/raspbian-stepmania-arcade/blob/master/Makefile#L45

Simply omitting that modprobe config *should* leave the RPi defaulting to "HDMI audio out along with HDMI video."

Although, depending on the HDMI display you are using, you may have to fiddle with the HDMI mode options, as described here: https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

I believe if you force it into DVI mode or DMT mode, you may have trouble getting the Pi to send audio over HDMI. So if you had to do that (or if you just got unlucky with the 'autodetect'), that might be blocking you.

I would _recommend_

1. make sure the config from `raspbian-stepmania-arcade` is not present in your `/etc/modprobe.d`
2. Look up the specs of your HDMI display and explicitly force `hdmi_drive=2` and `hdmi_group=1`, to help the Pi realize that it can send audio over HDMI. You may also have to actually explicitly configure your desired display resolution & refresh rate, too, if you're forcing autodetect off.
3. use the RPi GUI to select audio out over HDMI

Note:

I've not played around with tweaking the _build_ to use Jack. Jack... is usually a problem child every time I have to re-figure the dependencies to make the build work, or whenever there's a new RPi hardware or Raspian release. I can't offer you an experience-based advice for Jack.

**Comment by ColonelPanics** [comment]
@SpottyMatt thanks for such a thorough response, I shall take a look at some of the things you've mentioned now!

**Comment by ColonelPanics** [comment]
What surprises me is that audio out via HDMI works for other things on my Pi, I almost exclusively use the Pi for playing UltraStar Deluxe and have never once had audio issues 😕

**Comment by mikemintz** [comment]
I ran into the same issue on my 4b, and I was able to resolve it by modifying ~/.stepmania-5.1/Save/Preferences.ini and setting `SoundWriteAhead=2048`

My guess is that the `WARNING: ALSA: snd_pcm_wait: Broken pipe` log messages indicated buffer underruns.

**Comment by ColonelPanics** [comment]
I'll try this out tomorrow, I recently bought the soundcard recommended for Pi and that fixed audio issues but assumed there was something buffer-wise that could sort it (but went too far into trying to change that in pulseaudio, not in stepmania). If this works then I'll be returning to send you the biggest virtual hug ever for addressing this issue!!

**Comment by ColonelPanics** [comment]
Alright, I'm back after `>"tomorrow"` to confirm that @mikemintz's fix 100% works (and does notably have some "crackling" sound output every now and then alongside some song audio sounding a bit too slow, unlike other applications or when using the USB soundcard). Still good to know that this can work without the need for an extra peripheral, I do still wonder why the audio is so odd in this game. Other audio games (like Ultrastar) work without any audio issue remotely close to this level (anyway, that's getting off track)

**Comment by AlexGellert-zz** [comment]
> I ran into the same issue on my 4b, and I was able to resolve it by modifying ~/.stepmania-5.1/Save/Preferences.ini and setting `SoundWriteAhead=2048`
> 
> My guess is that the `WARNING: ALSA: snd_pcm_wait: Broken pipe` log messages indicated buffer underruns.

This enables HDMI to work.
